name: mtl-style-example
version: '0.0.0'
category: Other
synopsis: A small example of using mtl style to unit test effectful code.
description: A small example of using mtl style to unit test effectful code.
maintainer: Alexis King

extra-source-files:
- package.yaml
- README.md
- stack.yaml

ghc-options: -Wall
default-extensions:
- DefaultSignatures
- GADTs
- GeneralizedNewtypeDeriving
- LambdaCase
- OverloadedStrings

dependencies:
- base
- bytestring
- generic-lens
- microlens-platform
- fast-logger
- monad-logger
- monad-time
- mtl
- text
- time
- transformers
- freer-simple

library:
  source-dirs: library

executables:
  mtl-style-example:
    dependencies:
    - base
    - mtl-style-example
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    main: Main.hs
    source-dirs: executable

tests:
  mtl-style-example-test-suite:
    dependencies:
    - base
    - mtl-style-example
    - hspec
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    main: Main.hs
    source-dirs: test-suite
