resolver: lts-13.30

packages: 
- .
extra-deps:
- generic-lens-1.2.0.0
- git: https://github.com/FongHou/freer-simple.git
  commit: e0327d0c4a3de16a5bd1ff379bb5a392b59eacfe

flags: {}

extra-package-dbs: []
