resolver: lts-13.30

packages: 
- .
extra-deps:
- generic-lens-1.2.0.0
- polysemy-1.2.1.0
- first-class-families-0.6.0.0
- th-abstraction-0.3.1.0
- type-errors-0.2.0.0
- type-errors-pretty-0.0.0.0
- unagi-chan-0.4.1.2
- writer-cps-mtl-0.1.1.6
- writer-cps-transformers-0.5.6.1
- git: https://github.com/FongHou/freer-simple.git
  commit: 52d92c864c1db46582a2053a9f8e45c0ec6a8f52

flags: {}

extra-package-dbs: []
